[package]
name = "schedule-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
iced_aw = {version="0.9.3", default-features=false, features=["date_picker"]}
